[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_BACKEND_URL = "https://sgp-7-alumini-hub.onrender.com"
  VITE_APP_NAME = "Alumni Connect"
  VITE_API_BASE_URL = "https://sgp-7-alumini-hub.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200